In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('Crime_Data_from_2020_to_2024.csv')

In [3]:
df.head()
df.tail()
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004894 entries, 0 to 1004893
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1004894 non-null  int64
 1   Date Rptd       1004894 non-null  object
 2   DATE OCC        1004894 non-null  object
 3   TIME OCC        1004894 non-null  int64
 4   AREA            1004894 non-null  int64
 5   AREA NAME       1004894 non-null  object
 6   Rpt Dist No     1004894 non-null  int64
 7   Part 1-2        1004894 non-null  int64
 8   Crm Cd          1004894 non-null  int64
 9   Crm Cd Desc     1004894 non-null  object
 10  Mocodes         853296 non-null   object
 11  Vict Age        1004894 non-null  int64
 12  Vict Sex        860263 non-null   object
 13  Vict Descent    860251 non-null   object
 14  Premis Cd       1004878 non-null  float64
 15  Premis Desc     1004306 non-null  object
 16  Weapon Used Cd  327216 non-null   float64
 17  Weapon Desc     327216 non-null   object
 18  Status          1004893 non-null  object
 19  Status Desc     1004894 non-null  object
 20  Crm Cd 1        1004883 non-null  float64
 21  Crm Cd 2        69154 non-null    float64
 22  Crm Cd 3        2314 non-null     float64
 23  Crm Cd 4        64 non-null       float64
 24  LOCATION        1004894 non-null  object
 25  Cross Street    154228 non-null   object
 26  LAT             1004894 non-null  float64
 27  LON             1004894 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 164.8+ MB

(1004894, 28)

In [4]:
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,1.004894e+06,1.004894e+06,1.004894e+06,1.004894e+06,1.004894e+06,1.004894e+06,1.004894e+06,1.004878e+06,327216.000000,1.004883e+06,69154.000000,2314.000000,64.00000,1.004894e+06,1.004894e+06
mean,2.202190e+08,1.339901e+03,1.069153e+01,1.115613e+03,1.400313e+00,5.001386e+02,2.891862e+01,3.056108e+02,363.950797,4.998992e+02,958.097796,984.015990,991.21875,3.399820e+01,-1.180908e+02
std,1.319070e+07,6.510761e+02,6.110248e+00,6.111596e+02,4.899620e-01,2.052638e+02,2.199267e+01,2.192913e+02,123.737665,2.050643e+02,110.358509,52.350982,27.06985,1.610789e+00,5.582654e+00
min,8.170000e+02,1.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,1.100000e+02,-4.000000e+00,1.010000e+02,101.000000,1.100000e+02,210.000000,310.000000,821.00000,0.000000e+00,-1.186676e+02
25%,2.106168e+08,9.000000e+02,5.000000e+00,5.870000e+02,1.000000e+00,3.310000e+02,0.000000e+00,1.010000e+02,311.000000,3.310000e+02,998.000000,998.000000,998.00000,3.401470e+01,-1.184305e+02
50%,2.209158e+08,1.420000e+03,1.100000e+01,1.139000e+03,1.000000e+00,4.420000e+02,3.000000e+01,2.030000e+02,400.000000,4.420000e+02,998.000000,998.000000,998.00000,3.405890e+01,-1.183225e+02
75%,2.311102e+08,1.900000e+03,1.600000e+01,1.613000e+03,2.000000e+00,6.260000e+02,4.400000e+01,5.010000e+02,400.000000,6.260000e+02,998.000000,998.000000,998.00000,3.416490e+01,-1.182739e+02
max,2.521040e+08,2.359000e+03,2.100000e+01,2.199000e+03,2.000000e+00,9.560000e+02,1.200000e+02,9.760000e+02,516.000000,9.560000e+02,999.000000,999.000000,999.00000,3.433430e+01,0.000000e+00

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
DR_NO,1004894.0,2.202190e+08,1.319070e+07,817.0000,2.106168e+08,2.209158e+08,2.311102e+08,2.521040e+08
TIME OCC,1004894.0,1.339901e+03,6.510761e+02,1.0000,9.000000e+02,1.420000e+03,1.900000e+03,2.359000e+03
AREA,1004894.0,1.069153e+01,6.110248e+00,1.0000,5.000000e+00,1.100000e+01,1.600000e+01,2.100000e+01
Rpt Dist No,1004894.0,1.115613e+03,6.111596e+02,101.0000,5.870000e+02,1.139000e+03,1.613000e+03,2.199000e+03
Part 1-2,1004894.0,1.400313e+00,4.899620e-01,1.0000,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00
Crm Cd,1004894.0,5.001386e+02,2.052638e+02,110.0000,3.310000e+02,4.420000e+02,6.260000e+02,9.560000e+02
Vict Age,1004894.0,2.891862e+01,2.199267e+01,-4.0000,0.000000e+00,3.000000e+01,4.400000e+01,1.200000e+02
Premis Cd,1004878.0,3.056108e+02,2.192913e+02,101.0000,1.010000e+02,2.030000e+02,5.010000e+02,9.760000e+02
Weapon Used Cd,327216.0,3.639508e+02,1.237377e+02,101.0000,3.110000e+02,4.000000e+02,4.000000e+02,5.160000e+02
Crm Cd 1,1004883.0,4.998992e+02,2.050643e+02,110.0000,3.310000e+02,4.420000e+02,6.260000e+02,9.560000e+02
Crm Cd 2,69154.0,9.580978e+02,1.103585e+02,210.0000,9.980000e+02,9.980000e+02,9.980000e+02,9.990000e+02
Crm Cd 3,2314.0,9.840160e+02,5.235098e+01,310.0000,9.980000e+02,9.980000e+02,9.980000e+02,9.990000e+02
Crm Cd 4,64.0,9.912188e+02,2.706985e+01,821.0000,9.980000e+02,9.980000e+02,9.980000e+02,9.990000e+02
LAT,1004894.0,3.399820e+01,1.610789e+00,0.0000,3.401470e+01,3.405890e+01,3.416490e+01,3.433430e+01
LON,1004894.0,-1.180908e+02,5.582654e+00,-118.6676,-1.184305e+02,-1.183225e+02,-1.182739e+02,0.000000e+00

In [6]:
df.dtypes

DR_NO               int64
Date Rptd          object
DATE OCC           object
TIME OCC            int64
AREA                int64
AREA NAME          object
Rpt Dist No         int64
Part 1-2            int64
Crm Cd              int64
Crm Cd Desc        object
Mocodes            object
Vict Age            int64
Vict Sex           object
Vict Descent       object
Premis Cd         float64
Premis Desc        object
Weapon Used Cd    float64
Weapon Desc        object
Status             object
Status Desc        object
Crm Cd 1          float64
Crm Cd 2          float64
Crm Cd 3          float64
Crm Cd 4          float64
LOCATION           object
Cross Street       object
LAT               float64
LON               float64
dtype: object

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

DR_NO                   0
Date Rptd               0
DATE OCC                0
TIME OCC                0
AREA                    0
AREA NAME               0
Rpt Dist No             0
Part 1-2                0
Crm Cd                  0
Crm Cd Desc             0
Mocodes            151598
Vict Age                0
Vict Sex           144631
Vict Descent       144643
Premis Cd              16
Premis Desc           588
Weapon Used Cd     677678
Weapon Desc        677678
Status                  1
Status Desc             0
Crm Cd 1               11
Crm Cd 2           935740
Crm Cd 3          1002580
Crm Cd 4          1004830
LOCATION                0
Cross Street       850666
LAT                     0
LON                     0
dtype: int64

In [9]:
missing_df = df.isnull().sum().reset_index()
missing_df.columns = ['column', 'Missing_Values']
missing_df['Missing_Percent'] = (missing_df['Missing_Values'] / len(df)) * 100
missing_df.sort_values('Missing_Percent', ascending=False)

            column  Missing_Values  Missing_Percent
23        Crm Cd 4         1004830        99.993631
22        Crm Cd 3         1002580        99.769727
21        Crm Cd 2          935740        93.118279
25    Cross Street          850666        84.652312
16  Weapon Used Cd          677678        67.437760
17     Weapon Desc          677678        67.437760
10         Mocodes          151598        15.085969
13    Vict Descent          144643        14.393856
12        Vict Sex          144631        14.392662
15     Premis Desc             588         0.058514
14       Premis Cd              16         0.001592
20        Crm Cd 1              11         0.001095
18          Status               1         0.000100
26             LAT               0         0.000000
24        LOCATION               0         0.000000
19     Status Desc               0         0.000000
0            DR_NO               0         0.000000
1        Date Rptd               0         0.000000
11        Vict Age               0         0.000000
9      Crm Cd Desc               0         0.000000
8           Crm Cd               0         0.000000
7         Part 1-2               0         0.000000
6      Rpt Dist No               0         0.000000
5        AREA NAME               0         0.000000
4             AREA               0         0.000000
3         TIME OCC               0         0.000000
2         DATE OCC               0         0.000000
27             LON               0         0.000000

In [10]:
df.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='object')

In [11]:
df.columns = ( df.columns.str.lower(). str.replace (' ', '_') .str.replace(r'[()]', '', regex = True))

In [12]:
df.columns

Index(['dr_no', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name',
       'rpt_dist_no', 'part_1-2', 'crm_cd', 'crm_cd_desc', 'mocodes',
       'vict_age', 'vict_sex', 'vict_descent', 'premis_cd', 'premis_desc',
       'weapon_used_cd', 'weapon_desc', 'status', 'status_desc', 'crm_cd_1',
       'crm_cd_2', 'crm_cd_3', 'crm_cd_4', 'location', 'cross_street', 'lat',
       'lon'],
      dtype='object')

In [ ]:
df = df.drop(columns = ['crm_cd_2', 'crm_cd_3', 'crm_cd_4','cross_street','weapon_used_cd', 'weapon_desc',])

In [19]:
df = df.drop(columns = ['mocodes'])

In [30]:
df = df.drop(columns = ['crm_cd_1','premis_cd'])

In [31]:
df.columns

Index(['dr_no', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name',
       'rpt_dist_no', 'part_1-2', 'crm_cd', 'crm_cd_desc', 'vict_age',
       'vict_sex', 'vict_descent', 'premis_desc', 'status', 'status_desc',
       'location', 'lat', 'lon'],
      dtype='object')

In [27]:
df['vict_sex'] = df['vict_sex'].fillna('Unknown')
df['vict_descent'] = df['vict_descent'].fillna('Unknown')
df['premis_desc'] = df['premis_desc'].fillna('Unknown')
df['status'] = df['status'].fillna('Unknown')

In [33]:
df.isnull().sum()

dr_no           0
date_rptd       0
date_occ        0
time_occ        0
area            0
area_name       0
rpt_dist_no     0
part_1-2        0
crm_cd          0
crm_cd_desc     0
vict_age        0
vict_sex        0
vict_descent    0
premis_desc     0
status          0
status_desc     0
location        0
lat             0
lon             0
dtype: int64

In [34]:
df['date_rptd'] = pd.to_datetime(df['date_rptd'], errors = 'coerce')
df['date_occ'] = pd.to_datetime(df['date_occ'], errors = 'coerce')

<ipython-input-34-be8ff117696f>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date_rptd'] = pd.to_datetime(df['date_rptd'], errors = 'coerce')
<ipython-input-34-be8ff117696f>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date_occ'] = pd.to_datetime(df['date_occ'], errors = 'coerce')

In [35]:
df.head()

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,part_1-2,crm_cd,crm_cd_desc,vict_age,vict_sex,vict_descent,premis_desc,status,status_desc,location,lat,lon
0,211507896,2021-04-11,2020-11-07,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,31,M,H,SINGLE FAMILY DWELLING,IC,Invest Cont,7800 BEEMAN AV,34.2124,-118.4092
1,201516622,2020-10-21,2020-10-18,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",32,M,H,SIDEWALK,IC,Invest Cont,ATOLL AV,34.1993,-118.4203
2,240913563,2024-12-10,2020-10-30,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,30,M,W,SINGLE FAMILY DWELLING,IC,Invest Cont,14600 SYLVAN ST,34.1847,-118.4509
3,210704711,2020-12-24,2020-12-24,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,47,F,A,STREET,IC,Invest Cont,6000 COMEY AV,34.0339,-118.3747
4,201418201,2020-10-03,2020-09-29,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),63,M,H,ALLEY,IC,Invest Cont,4700 LA VILLA MARINA,33.9813,-118.4350

In [ ]:
df.to_csv('Cleaned_Crime.csv', index= False)