In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('google_play_store_dataset.csv')

In [3]:
df.head()
df.tail()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 592.9+ KB

In [4]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [5]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [6]:
df.describe().T

         count      mean       std  min  25%  50%  75%   max
Rating  9367.0  4.193338  0.537431  1.0  4.0  4.3  4.5  19.0

In [7]:
df.duplicated().sum()

np.int64(483)

In [8]:
df = df.drop_duplicates()

In [9]:
print(df.duplicated().sum())

0

In [10]:
df.isnull().sum()

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [11]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [12]:
df.columns = ( df.columns.str.lower(). str.replace (' ', '_') .str.replace(r'[()]', '', regex = True))

In [13]:
df.columns

Index(['app', 'category', 'rating', 'reviews', 'size', 'installs', 'type',
       'price', 'content_rating', 'genres', 'last_updated', 'current_ver',
       'android_ver'],
      dtype='object')

In [18]:
df['installs'] = df['installs'].str.replace('+', '', regex= False)
df['installs'] = df['installs'].str.replace(',', '', regex= False)

df['installs'] = pd.to_numeric(df['installs'],errors='coerce')

In [20]:
df['price'] = df['price'].str.replace('$','',regex=False)

df['price'] = pd.to_numeric(df['price'],errors='coerce')

In [21]:
df['rating'] = df['rating'].fillna(df['rating'].mean())

In [22]:
df['rating'] = pd.to_numeric(df['rating'],errors='coerce')

In [23]:
df['type'] = df['type'].fillna('Unknown')
df['content_rating'] = df['content_rating'].fillna('Unknown')
df['current_ver'] = df['current_ver'].fillna('Unknown')
df['android_ver'] = df['android_ver'].fillna('Unknown')

In [30]:
df['rating_class'] = df['rating'].apply(lambda x: 1 if x >= 4 else 0)

In [35]:
# Features

X = df[['reviews','installs', 'price']]
y = df['rating_class']

In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [37]:
model = LogisticRegression()
model.fit(X_train, y_train)

/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [39]:
predictions = model.predict(X_test)
print(predictions)

[1 1 1 ... 1 1 1]

In [ ]:
# Visualization

plt.scatter(df['installs'], df['rating'])