In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('acc_16.csv')

In [3]:
df.head()
df.tail()
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46511 entries, 0 to 46510
Data columns (total 51 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CASENUM     46511 non-null  int64
 1   PSU         46511 non-null  int64
 2   PJ          46511 non-null  int64
 3   STRATUM     46511 non-null  int64
 4   VE_TOTAL    46511 non-null  int64
 5   VE_FORMS    46511 non-null  int64
 6   PVH_INVL    46511 non-null  int64
 7   PEDS        46511 non-null  int64
 8   PERMVIT     46511 non-null  int64
 9   PERNOTMVIT  46511 non-null  int64
 10  NUM_INJ     46511 non-null  int64
 11  MONTH       46511 non-null  int64
 12  YEAR        46511 non-null  int64
 13  DAY_WEEK    46511 non-null  int64
 14  HOUR        46511 non-null  int64
 15  MINUTE      46511 non-null  int64
 16  HARM_EV     46511 non-null  int64
 17  ALCOHOL     46511 non-null  int64
 18  MAX_SEV     46511 non-null  int64
 19  MAN_COLL    46511 non-null  int64
 20  RELJCT1     46511 non-null  int64
 21  RELJCT2     46511 non-null  int64
 22  TYP_INT     46511 non-null  int64
 23  WRK_ZONE    46511 non-null  int64
 24  REL_ROAD    46511 non-null  int64
 25  LGT_COND    46511 non-null  int64
 26  WEATHER1    46511 non-null  int64
 27  WEATHER2    46511 non-null  int64
 28  WEATHER     46511 non-null  int64
 29  SCH_BUS     46511 non-null  int64
 30  INT_HWY     46511 non-null  int64
 31  CF1         46511 non-null  int64
 32  CF2         46511 non-null  int64
 33  CF3         46511 non-null  int64
 34  WKDY_IM     46511 non-null  int64
 35  HOUR_IM     46511 non-null  int64
 36  MINUTE_IM   46511 non-null  int64
 37  EVENT1_IM   46511 non-null  int64
 38  MANCOL_IM   46511 non-null  int64
 39  RELJCT1_IM  46511 non-null  int64
 40  RELJCT2_IM  46511 non-null  int64
 41  LGTCON_IM   46511 non-null  int64
 42  WEATHR_IM   46511 non-null  int64
 43  MAXSEV_IM   46511 non-null  int64
 44  NO_INJ_IM   46511 non-null  int64
 45  ALCHL_IM    46511 non-null  int64
 46  URBANICITY  46511 non-null  int64
 47  REGION      46511 non-null  int64
 48  PSUSTRAT    46511 non-null  int64
 49  PSU_VAR     46511 non-null  int64
 50  WEIGHT      46511 non-null  float64
dtypes: float64(1), int64(50)
memory usage: 18.1 MB

(46511, 51)

In [4]:
df.dtypes

CASENUM         int64
PSU             int64
PJ              int64
STRATUM         int64
VE_TOTAL        int64
VE_FORMS        int64
PVH_INVL        int64
PEDS            int64
PERMVIT         int64
PERNOTMVIT      int64
NUM_INJ         int64
MONTH           int64
YEAR            int64
DAY_WEEK        int64
HOUR            int64
MINUTE          int64
HARM_EV         int64
ALCOHOL         int64
MAX_SEV         int64
MAN_COLL        int64
RELJCT1         int64
RELJCT2         int64
TYP_INT         int64
WRK_ZONE        int64
REL_ROAD        int64
LGT_COND        int64
WEATHER1        int64
WEATHER2        int64
WEATHER         int64
SCH_BUS         int64
INT_HWY         int64
CF1             int64
CF2             int64
CF3             int64
WKDY_IM         int64
HOUR_IM         int64
MINUTE_IM       int64
EVENT1_IM       int64
MANCOL_IM       int64
RELJCT1_IM      int64
RELJCT2_IM      int64
LGTCON_IM       int64
WEATHR_IM       int64
MAXSEV_IM       int64
NO_INJ_IM       int64
ALCHL_IM        int64
URBANICITY      int64
REGION          int64
PSUSTRAT        int64
PSU_VAR         int64
WEIGHT        float64
dtype: object

In [5]:
df.describe()

,CASENUM,PSU,PJ,STRATUM,VE_TOTAL,VE_FORMS,PVH_INVL,PEDS,PERMVIT,PERNOTMVIT,...,LGTCON_IM,WEATHR_IM,MAXSEV_IM,NO_INJ_IM,ALCHL_IM,URBANICITY,REGION,PSUSTRAT,PSU_VAR,WEIGHT
count,4.651100e+04,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,...,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000,46511.000000
mean,2.016005e+11,44.719443,1347.937563,7.229602,1.814969,1.766227,0.048741,0.085915,2.438240,0.093612,...,1.577541,2.570510,0.996108,0.792479,1.940294,1.248414,2.750425,12.630324,46.712563,146.656253
std,2.620586e+05,18.314777,994.650630,2.521382,0.653581,0.649184,0.263875,0.292039,1.485343,0.315595,...,1.030768,3.241848,1.162023,1.004280,0.236944,0.432098,0.811031,5.815995,25.979351,108.840715
min,2.016000e+11,10.000000,46.000000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,10.000000,3.861913
25%,2.016003e+11,31.000000,464.000000,6.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,2.000000,1.000000,2.000000,8.000000,31.000000,54.086403
50%,2.016005e+11,41.000000,1078.000000,8.000000,2.000000,2.000000,0.000000,0.000000,2.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,13.000000,41.000000,142.958641
75%,2.016007e+11,59.000000,2087.000000,9.000000,2.000000,2.000000,0.000000,0.000000,3.000000,0.000000,...,2.000000,2.000000,2.000000,1.000000,2.000000,1.000000,3.000000,16.000000,60.000000,204.297900
max,2.016010e+11,82.000000,4036.000000,10.000000,11.000000,8.000000,9.000000,6.000000,24.000000,6.000000,...,7.000000,12.000000,8.000000,16.000000,2.000000,2.000000,4.000000,25.000000,206.000000,994.507448

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
CASENUM,46511.0,2.016005e+11,262058.643462,2.016000e+11,2.016003e+11,2.016005e+11,2.016007e+11,2.016010e+11
PSU,46511.0,4.471944e+01,18.314777,1.000000e+01,3.100000e+01,4.100000e+01,5.900000e+01,8.200000e+01
PJ,46511.0,1.347938e+03,994.650630,4.600000e+01,4.640000e+02,1.078000e+03,2.087000e+03,4.036000e+03
STRATUM,46511.0,7.229602e+00,2.521382,2.000000e+00,6.000000e+00,8.000000e+00,9.000000e+00,1.000000e+01
VE_TOTAL,46511.0,1.814969e+00,0.653581,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,1.100000e+01
VE_FORMS,46511.0,1.766227e+00,0.649184,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,8.000000e+00
PVH_INVL,46511.0,4.874116e-02,0.263875,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00
PEDS,46511.0,8.591516e-02,0.292039,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e+00
PERMVIT,46511.0,2.438240e+00,1.485343,0.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,2.400000e+01
PERNOTMVIT,46511.0,9.361226e-02,0.315595,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e+00
NUM_INJ,46511.0,2.612887e+00,13.318839,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,9.900000e+01
MONTH,46511.0,6.456086e+00,3.425887,1.000000e+00,3.000000e+00,6.000000e+00,9.000000e+00,1.200000e+01
YEAR,46511.0,2.016000e+03,0.000000,2.016000e+03,2.016000e+03,2.016000e+03,2.016000e+03,2.016000e+03
DAY_WEEK,46511.0,4.127325e+00,1.916242,1.000000e+00,3.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
HOUR,46511.0,1.348262e+01,6.342818,0.000000e+00,9.000000e+00,1.400000e+01,1.700000e+01,9.900000e+01
MINUTE,46511.0,2.827925e+01,17.804903,0.000000e+00,1.300000e+01,2.900000e+01,4.400000e+01,9.900000e+01
HARM_EV,46511.0,1.536387e+01,10.384947,1.000000e+00,1.200000e+01,1.200000e+01,1.200000e+01,9.900000e+01
ALCOHOL,46511.0,2.934166e+00,2.463670,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,9.000000e+00
MAX_SEV,46511.0,1.135452e+00,1.574514,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,9.000000e+00
MAN_COLL,46511.0,2.789598e+00,6.197250,0.000000e+00,0.000000e+00,1.000000e+00,6.000000e+00,9.900000e+01
RELJCT1,46511.0,1.776139e-01,1.127839,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00
RELJCT2,46511.0,3.169444e+00,8.615382,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,9.900000e+01
TYP_INT,46511.0,1.066352e+01,28.261011,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,9.900000e+01
WRK_ZONE,46511.0,5.860979e-02,0.443259,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
REL_ROAD,46511.0,1.759799e+00,3.156365,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.900000e+01
LGT_COND,46511.0,1.621315e+00,1.166482,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,9.000000e+00
WEATHER1,46511.0,5.807981e+00,17.596507,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,9.900000e+01
WEATHER2,46511.0,2.532734e-02,0.646146,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.800000e+01
WEATHER,46511.0,5.803014e+00,17.596364,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,9.900000e+01
SCH_BUS,46511.0,5.310572e-03,0.072681,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
INT_HWY,46511.0,8.331362e-02,0.295314,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00
CF1,46511.0,9.488293e-01,5.210153,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.900000e+01
CF2,46511.0,1.230032e-01,2.991140,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.900000e+01
CF3,46511.0,8.258261e-02,2.834956,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.900000e+01
WKDY_IM,46511.0,4.127325e+00,1.916242,1.000000e+00,3.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
HOUR_IM,46511.0,1.334858e+01,5.365893,0.000000e+00,9.000000e+00,1.400000e+01,1.700000e+01,2.300000e+01
MINUTE_IM,46511.0,2.816848e+01,17.591206,0.000000e+00,1.300000e+01,2.900000e+01,4.400000e+01,5.900000e+01
EVENT1_IM,46511.0,1.533089e+01,10.227023,1.000000e+00,1.200000e+01,1.200000e+01,1.200000e+01,7.400000e+01
MANCOL_IM,46511.0,2.478467e+00,2.877818,0.000000e+00,0.000000e+00,1.000000e+00,6.000000e+00,1.100000e+01
RELJCT1_IM,46511.0,1.896326e-02,0.136397,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
RELJCT2_IM,46511.0,2.462708e+00,2.606836,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,2.000000e+01
LGTCON_IM,46511.0,1.577541e+00,1.030768,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,7.000000e+00
WEATHR_IM,46511.0,2.570510e+00,3.241848,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.200000e+01
MAXSEV_IM,46511.0,9.961084e-01,1.162023,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,8.000000e+00
NO_INJ_IM,46511.0,7.924792e-01,1.004280,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.600000e+01
ALCHL_IM,46511.0,1.940294e+00,0.236944,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00
URBANICITY,46511.0,1.248414e+00,0.432098,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00
REGION,46511.0,2.750425e+00,0.811031,1.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00
PSUSTRAT,46511.0,1.263032e+01,5.815995,1.000000e+00,8.000000e+00,1.300000e+01,1.600000e+01,2.500000e+01
PSU_VAR,46511.0,4.671256e+01,25.979351,1.000000e+01,3.100000e+01,4.100000e+01,6.000000e+01,2.060000e+02
WEIGHT,46511.0,1.466563e+02,108.840715,3.861913e+00,5.408640e+01,1.429586e+02,2.042979e+02,9.945074e+02

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

CASENUM       0
PSU           0
PJ            0
STRATUM       0
VE_TOTAL      0
VE_FORMS      0
PVH_INVL      0
PEDS          0
PERMVIT       0
PERNOTMVIT    0
NUM_INJ       0
MONTH         0
YEAR          0
DAY_WEEK      0
HOUR          0
MINUTE        0
HARM_EV       0
ALCOHOL       0
MAX_SEV       0
MAN_COLL      0
RELJCT1       0
RELJCT2       0
TYP_INT       0
WRK_ZONE      0
REL_ROAD      0
LGT_COND      0
WEATHER1      0
WEATHER2      0
WEATHER       0
SCH_BUS       0
INT_HWY       0
CF1           0
CF2           0
CF3           0
WKDY_IM       0
HOUR_IM       0
MINUTE_IM     0
EVENT1_IM     0
MANCOL_IM     0
RELJCT1_IM    0
RELJCT2_IM    0
LGTCON_IM     0
WEATHR_IM     0
MAXSEV_IM     0
NO_INJ_IM     0
ALCHL_IM      0
URBANICITY    0
REGION        0
PSUSTRAT      0
PSU_VAR       0
WEIGHT        0
dtype: int64

In [10]:
# Feature and target

X = df.drop('MAX_SEV', axis=1)
y = df['MAX_SEV']

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [14]:
y_pred = model.predict(X_test)